
project_id = "ldhnqpkaifyoxtuchxko"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "https://industry-mailbox.lovable.app"
additional_redirect_urls = [
  "https://feb48f71-47d1-4ebf-85de-76618e7c453a.lovableproject.com/admin", 
  "https://preview--industry-mailbox.lovable.app",
  "https://preview--industry-mailbox.lovable.app/admin",
  "https://industry-mailbox.lovable.app",
  "https://industry-mailbox.lovable.app/admin"
]

[functions.connect-gmail]
verify_jwt = false

[functions.sync-emails]
verify_jwt = false
