
project_id = "ldhnqpkaifyoxtuchxko"

[functions.connect-gmail]
verify_jwt = false

[functions.disconnect-notification]
verify_jwt = false

[functions.sync-emails]
verify_jwt = false

[functions.update-admin-stats]
verify_jwt = false

[functions.debug-test]
verify_jwt = false
