
project_id = "ldhnqpkaifyoxtuchxko"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[[functions]]
name = "connect-gmail"
verify_jwt = false

[[functions]]
name = "sync-emails"
verify_jwt = false
