// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldhnqpkaifyoxtuchxko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkaG5xcGthaWZ5b3h0dWNoeGtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2NzM2MjksImV4cCI6MjA1NjI0OTYyOX0.LWswKYTJsMAZ_jl1CZN_gt30tCfFTN78yce_15kb3Yo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);